development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: supr_star_dev
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: supr_star_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: supr_star_production
  pool: 5
  timeout: 5000